In [1]:
import pandas as pd
import numpy as np

In [5]:
a_bdnn_rep_4 = pd.read_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_4_G_BDS_BDNN_4_2Tc_mcmc.log", sep="\t", header=0)
a_bdnn_rep_4.describe()

,it,posterior,prior,PP_lik,BD_lik,q_0,q_1,q_2,q_3,q_4,...,Yelaphomte_TE,Yimenosaurus_TE,Youngetta_TE,Youngina_TE,Youngosuchus_TE,Yunguisaurus_TE,Yunnanosaurus_TE,Zanclodon_TE,Zhongjiania_TE,Zupaysaurus_TE
count,9.693000e+03,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,...,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000
mean,4.846000e+07,-16921.714012,-2200.535270,-10616.733448,-4104.445295,0.686177,5.215353,0.878803,1.310975,2.430629,...,49.783495,24.385640,75.266885,76.284624,71.585801,61.359895,25.673319,27.263383,79.307226,47.777007
std,2.798272e+07,83.369567,13.142674,48.843440,51.939738,0.228424,0.360970,0.180667,0.344515,0.341176,...,0.958016,0.335684,0.375294,1.305898,0.457496,1.538418,0.513775,1.631867,0.562239,0.868704
min,0.000000e+00,-21792.450507,-2237.064142,-11981.405312,-7738.214920,0.188454,0.370792,0.370792,0.370792,0.370792,...,41.472211,21.107097,71.768193,64.341286,67.302719,51.900640,19.556576,18.030161,72.220950,41.919526
25%,2.423000e+07,-16957.780476,-2208.012767,-10646.210464,-4113.972388,0.530206,4.977896,0.740142,1.067608,2.196133,...,49.550209,24.262202,75.162315,75.811032,71.471557,60.736297,25.542419,26.445395,79.150294,47.498972
50%,4.846000e+07,-16918.003652,-2201.152604,-10615.929466,-4100.129786,0.652367,5.216158,0.873919,1.280274,2.406863,...,50.123677,24.490054,75.398168,76.715512,71.750083,61.915054,25.843795,27.706333,79.465298,48.089558
75%,7.269000e+07,-16878.386231,-2194.579236,-10585.247380,-4087.214055,0.805875,5.450380,1.009955,1.522991,2.637751,...,50.384068,24.621657,75.512523,77.184692,71.879284,62.487983,25.994106,28.546175,79.651815,48.374086
max,9.692000e+07,-16724.404910,-2072.830274,-10398.689248,-4028.669482,2.638998,6.729365,1.651070,4.113144,5.166731,...,50.522489,24.713129,75.567580,77.436463,71.936261,62.766438,26.106801,29.142904,79.791650,48.512072

In [15]:
a_bdnn_rep_4_sp_rates = pd.read_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_4_G_BDS_BDNN_4_2Tc_sp_rates.log", sep="\t", header=0)
a_bdnn_rep_4_sp_rates.describe()

,0.7021791291715602,0.702179124256164,0.7021791187087707,0.7021791131613488,0.7021791076138986,0.7021791020664202,0.7021790965189137,0.7021790909713798,0.7021790854238181,0.7021790798762295,...,10,9,8,7,6,5,4,3,2,1
count,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,...,9693.0,9693.0,9693.0,9693.0,9693.0,9693.0,9693.0,9693.0,9693.0,9693.0
mean,0.322846,0.323297,0.323810,0.324328,0.324850,0.325376,0.325904,0.326433,0.326962,0.327491,...,10.0,9.0,8.0,7.0,6.0,5.0,4.0,3.0,2.0,1.0
std,0.047138,0.046647,0.046081,0.045504,0.044915,0.044314,0.043702,0.043078,0.042442,0.041795,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,0.134854,0.134855,0.134857,0.134859,0.134861,0.134864,0.134866,0.134868,0.134870,0.134873,...,10.0,9.0,8.0,7.0,6.0,5.0,4.0,3.0,2.0,1.0
25%,0.290628,0.291371,0.292275,0.293205,0.294078,0.295115,0.296074,0.297110,0.298044,0.299029,...,10.0,9.0,8.0,7.0,6.0,5.0,4.0,3.0,2.0,1.0
50%,0.324802,0.325192,0.325588,0.326045,0.326593,0.327092,0.327469,0.327883,0.328423,0.328864,...,10.0,9.0,8.0,7.0,6.0,5.0,4.0,3.0,2.0,1.0
75%,0.355585,0.355630,0.355694,0.355777,0.355888,0.355909,0.356027,0.356080,0.356219,0.356194,...,10.0,9.0,8.0,7.0,6.0,5.0,4.0,3.0,2.0,1.0
max,0.515050,0.513531,0.511751,0.509897,0.507968,0.505959,0.503868,0.501690,0.499423,0.497063,...,10.0,9.0,8.0,7.0,6.0,5.0,4.0,3.0,2.0,1.0

In [16]:
a_bdnn_rep_4_sp_rates.head()

,0.7021791291715602,0.702179124256164,0.7021791187087707,0.7021791131613488,0.7021791076138986,0.7021791020664202,0.7021790965189137,0.7021790909713798,0.7021790854238181,0.7021790798762295,...,10,9,8,7,6,5,4,3,2,1
0,0.141480,0.141485,0.141491,0.141497,0.141503,0.141509,0.141515,0.141522,0.141528,0.141534,...,10,9,8,7,6,5,4,3,2,1
1,0.139298,0.139337,0.139380,0.139424,0.139468,0.139512,0.139556,0.139600,0.139645,0.139690,...,10,9,8,7,6,5,4,3,2,1
2,0.148296,0.148297,0.148297,0.148298,0.148299,0.148299,0.148300,0.148301,0.148301,0.148302,...,10,9,8,7,6,5,4,3,2,1
3,0.148448,0.148449,0.148451,0.148452,0.148453,0.148455,0.148456,0.148458,0.148459,0.148460,...,10,9,8,7,6,5,4,3,2,1
4,0.140448,0.140450,0.140452,0.140455,0.140457,0.140459,0.140462,0.140464,0.140467,0.140469,...,10,9,8,7,6,5,4,3,2,1

In [17]:
a_bdnn_rep_4.shape, a_bdnn_rep_4_sp_rates.shape

((9693, 1576), (9693, 247))

In [18]:
# A fully completed A_bdnn
a_bdnn_tem_1 = pd.read_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/temnospondyli/mcmc_no_predictors/A_bdnn_update/temnospondyli_pyrate_1_A_update_G_BDS_BDNN_4_2Tc_mcmc.log", sep="\t", header=0)
a_bdnn_tem_1_sp_rates = pd.read_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/temnospondyli/mcmc_no_predictors/A_bdnn_update/temnospondyli_pyrate_1_A_update_G_BDS_BDNN_4_2Tc_sp_rates.log", sep="\t", header=0)

a_bdnn_tem_1.shape, a_bdnn_tem_1_sp_rates.shape

((10000, 612), (9999, 269))

In [19]:
a_bdnn_tem_1_sp_rates.head()

,0.699868417722341,0.6998684194736766,0.6998684214834019,0.6998684234931282,0.6998684255028562,0.6998684275125848,0.6998684295223149,0.699868431532046,0.6998684335417787,0.6998684355515122,...,10,9,8,7,6,5,4,3,2,1
0,0.146344,0.146344,0.146345,0.146346,0.146347,0.146348,0.146349,0.146350,0.146351,0.146352,...,10,9,8,7,6,5,4,3,2,1
1,0.132279,0.132350,0.132429,0.132507,0.132584,0.132660,0.132734,0.132806,0.132877,0.132947,...,10,9,8,7,6,5,4,3,2,1
2,0.158456,0.158075,0.157637,0.157196,0.156753,0.156308,0.155861,0.155412,0.154960,0.154507,...,10,9,8,7,6,5,4,3,2,1
3,0.148230,0.148225,0.148219,0.148213,0.148207,0.148200,0.148194,0.148187,0.148181,0.148174,...,10,9,8,7,6,5,4,3,2,1
4,0.151888,0.151887,0.151886,0.151886,0.151885,0.151885,0.151884,0.151884,0.151884,0.151883,...,10,9,8,7,6,5,4,3,2,1

In [20]:
a_bdnn_tem_2_sp_rates = pd.read_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/temnospondyli/mcmc_no_predictors/A_bdnn_update/temnospondyli_pyrate_2_A_update_G_BDS_BDNN_4_2Tc_sp_rates.log", sep="\t", header=0)
a_bdnn_tem_2_sp_rates.shape

(9999, 269)